### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by arkade23** [hiwad-aziz/ros2_mpu9250_driver#3]
Hello!

First of all thanks for the great work on this driver!
I had a question regarding this project's licensing.  I wanted to include your driver in one of my uni's projects and I noticed you didnt inlcude any license but the repo is public. 
According to this: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
"no one may reproduce, distribute, or create derivative works" if there is no license. So would you be interested to update your repo in the coming future in order for more people to be able to use your code?

**Comment by hiwad-aziz** [comment]
Hi @EleniNkl, 
feel free to use it in your uni project. I have added the MIT license and hope it fits your needs.
